sudo: required

services:
  - docker                  

before_install:            
  - curl -L -o jbake.zip https://dl.bintray.com/jbake/binary/jbake-2.6.0-bin.zip
  - unzip jbake.zip && rm -f jbake.zip

script:
  - jbake-*/bin/jbake -b

after_error: 
  - docker logs jbake

after_failure:
  - docker logs jbake

after_success:
  - cp CNAME output/
  - cd output
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master