sudo: required

services:
  - docker                  

before_install:            
  - docker pull mwilmes/docker-jbake

script:
  - docker run -t -i --rm -v $TRAVIS_BUILD_DIR:/mnt/blog --name jbake mwilmes/docker-jbake jbake /mnt/blog /mnt/blog/output

after_error: 
  - docker logs jbake

after_failure:
  - docker logs jbake

after_success:      
  - cd output
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages