= jitpack.io for Gradle Plugins
.
2020-06-29
:jbake-type: post
:jbake-tags: gradle eclipse
:jbake-status: published

I extensively use the link:https://github.com/TwoStone/gradle-eclipse-compiler-plugin[gradle-eclipse-compiler-plugin]. This is a Gradle plugin that allows me to use the Eclipse JDT compiler for my Gradle builds instead of standard `javac` of my installed JDK.
Why is this useful? Because when I deploy e.g. a WAR file built with Gradle to an app-server and want to do remote-debugging and also hot-swap code in the debug session from my IDE, it is better to use the same compiler for both IDE and Gradle.
Otherwise this causes problems where constructs like lambda expression are compiled differently and the debug-session will not be able to swap the code; e.g. saying that methods where added or removed.

But this post is not about the usefulness of the plugin itself, but rather that it stopped working for me with Gradle 6 and I quickly wanted a fix that I can also distribute to other people.
Obviously, I filed an issue and made a pull-request; but until the pull-request is merged how provide the fix to others?
Meet link:https://jitpack.io/#38leinaD/gradle-eclipse-compiler-plugin/fix~unrecognized-option-SNAPSHOT[jitpack.io] which provides a maven repository for all of Github. You can request artifacts from this repository and what it will do is check out the code from GitHub and build it on the fly. You can use the version to reference specific branches or commits.


So, to use my fix/PR, I had to add the following to my Gradle project:

[source, groovy]
----
buildscript {
    repositories {
            maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath group: 'com.github.38leinaD', name: 'gradle-eclipse-compiler-plugin', version: 'fix~unrecognized-option-SNAPSHOT'
    }
}

apply plugin: 'de.set.ecj'
----

