= Gradle and Arquillian for OpenLiberty
.
2018-02-28
:jbake-type: post
:jbake-tags: gradle wildfly arquillian
:jbake-status: published

In this post I describe how to set up arquillian to test/deploy on Wildfly.
Note that there is a managed and a remote-adapter.
Managed will mean that arquillian manages the application-server and thus starts it.
Remote means that the application-server was already started somehow and arquillian will only connect and deploy the application within this remote server.
Below you will find the dependencies for both types of adpaters.

[source, groovy]
----
dependencies {
    providedCompile 'javax:javaee-api:7.0'

	// this is the BOM
	testCompile 'org.jboss.arquillian:arquillian-bom:1.3.0.Final'
	testCompile 'org.jboss.arquillian.junit:arquillian-junit-container'
	
	testCompile 'org.wildfly.arquillian:wildfly-arquillian-container-managed:2.1.0.Final'
	testCompile 'org.wildfly.arquillian:wildfly-arquillian-container-remote:2.1.0.Final'

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:2.10.0'
}
----

An `arquillian.xml` for both adapters looks like the following. The `arquillian-wildfly-managed` config is enabled here by default.

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://jboss.org/schema/arquillian"
    xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

	<engine>
		<property name="deploymentExportPath">build/deployments</property>
	</engine>

	<!-- Start JBoss manually via:
		./standalone.sh -Djboss.socket.binding.port-offset=100 -server-config=standalone-full.xml
	 -->
	<container qualifier="arquillian-wildfly-remote">
		<configuration>
			<property name="managementPort">10090</property>
		</configuration>
	</container>

	<container qualifier="arquillian-wildfly-managed" default="true">
		<configuration>
			<property name="jbossHome">/home/daniel/dev/app-servers/jboss-eap-7.0-test</property>
			<property name="serverConfig">${jboss.server.config.file.name:standalone-full.xml}</property>
			<property name="allowConnectingToRunningServer">true</property>
		</configuration>
	</container>
</arquillian>
----

As an additional tip: I always set `deploymentExportPath` to a folder withing gradle's build-directory because sometimes it is helpful to have a look at the deployment generated by arquillian/shrinkwrap.

In case you don't want to define a default adapater or overwrite it (e.g. via a gradle-property from the commandline), you can define the `arquillian.launch` system property within the test-configuration.

----
test {
	systemProperty "arquillian.launch", "arquillian-wildfly-managed"
}
----
