= Gradle and Arquillian Chameleon even simpler
.
2018-04-07
:jbake-type: post
:jbake-tags: gradle javaee arquillian wildfly
:jbake-status: published

In a previous post I have already described how to use Arquillian Chameleon to simplify the Arquillian config.

With the latest improvements that are described link:http://www.lordofthejars.com/2018/03/arquillian-chameleon-simplifying-your.html[here] in more detail,
it is now possible to minimize the require configuration:

* Only a single dependency
* No `arquillian.xml`

As before, I assume  Gradle 4.6 with `enableFeaturePreview('IMPROVED_POM_SUPPORT')` in the `settings.gradle` to enable the advanced POM-support.

With this, we only have to add a single dependency to use arquillian:

[source, groovy]
----
dependencies {
    providedCompile 'javax:javaee-api:7.0'

    testCompile 'org.arquillian.container:arquillian-chameleon-junit-container-starter:1.0.0.CR2'

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:2.10.0'
}
----

The container which is used, only need to be defined via the `@ChameleonTarget` annotation.
Also note the new `@RunWith(ArquillianChameleon.class)`. This not the regular `@RunWith(ArquillianChameleon.class).

[source, java]
----
@RunWith(ArquillianChameleon.class)
@ChameleonTarget("wildfly:11.0.0.Final:managed")
public class GreetingServiceTest {

    @Deployment
    public static WebArchive deployService() {
        return ShrinkWrap.create(WebArchive.class)
                .addClass(Service.class);
    }

    @Inject
    private Service service;

    @Test
    public void shouldGreetTheWorld() throws Exception {
        Assert.assertEquals("hello world", service.hello());
    }
}
----

There is also support now for not having to write the `@Deployment` method. Up to now, only for maven-build and specifing a local file.