= Websphere Traditional, Docker and Auto-Deployment
.
2018-04-10
:jbake-type: post
:jbake-tags: websphere docker
:jbake-status: published

The software I work with on my job is portable accross different application-servers; including Websphere Trational, Websphere Liberty and JBoss.
In the past, it took cosiderable time for me to test/make sure a feature works as expected on Websphere.
In part, because it was hard for me to keep all different websphere version installed on my machine and not mess them up over time.

Now, with the link:https://hub.docker.com/r/ibmcom/websphere-traditional/[docker images provided by IBM], it has become very easy.
Just fire up a container and test it.

To make the testing/deployment very easy, I have enabled auto-deploy in link:https://github.com/38leinaD/docker-images/tree/master/websphere-9[my container-image].

The image contains a jython script so you don't have to apply this configuration manually.

[source, python]
----
import java.lang.System as sys

cell = AdminConfig.getid('/Cell:DefaultCell01/')
md = AdminConfig.showAttribute(cell, "monitoredDirectoryDeployment")
AdminConfig.modify(md, [['enabled', "true"]])
AdminConfig.modify(md, [['pollingInterval', "1"]])

print AdminConfig.show(md)

AdminConfig.save()

print 'Done.'
----


It allows me to work with VSCode and Gradle as I have described in link:http://dplatz.de/blog/2018/redeploy.html[this post].

Start the docker container with below command to mount the auto-deploy folder as a volume:

----
docker run --name was9 --rm -p 9060:9060 -p 9080:9080 -p 7777:7777 -v ~/junk/deploy:/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/monitoredDeployableApps 38leinad/websphere-9
----

You can now copy a WAR file to `~/junk/deploy/servers/server1/` on your local system and it will get deployed automatically within the container.
