= Open Liberty with DerbyDB
.
2018-03-13
:jbake-type: post
:jbake-tags: wlp, javaee, derby
:jbake-status: published

In this post I describe how to use Open Liberty with the lightweight Apache Derby database.

Here are the steps:

. Download link:https://db.apache.org/derby/releases/release-10.14.1.0.cgi[Apache Derby].

. Configure the driver/datasource in the `server.xml`
+
[source, xml]
----
    <!-- https://www.ibm.com/support/knowledgecenter/de/SS7K4U_liberty/com.ibm.websphere.wlp.zseries.doc/ae/twlp_dep_configuring_ds.html -->
    <variable name="DERBY_JDBC_DRIVER_PATH" value="/home/daniel/dev/tools/db-derby-10.14.1.0-bin/lib"/>
    <library id="DerbyLib">
        <fileset dir="${DERBY_JDBC_DRIVER_PATH}"/>
    </library>
    <dataSource id="DefaultDerbyDatasource" jndiName="jdbc/defaultDatasource" statementCacheSize="10" transactional="true">
       <jdbcDriver libraryRef="DerbyLib"/>
       <properties.derby.embedded connectionAttributes="upgrade=true" createDatabase="create" databaseName="/var/tmp/sample.embedded.db" shutdownDatabase="false"/>
	   <!--properties.derby.client databaseName="/var/tmp/sample.db" user="derbyuser" password="derbyuser" createDatabase="create" serverName="localhost" portNumber="1527" traceLevel="1"/-->
    </dataSource>
----
+
Note that the database is embeeded and file-based. This means, no database-server needs to be started manually.
On application-server startup an embeeded database is started and will write to the file under `databaseName`.
Use the `memory:` prefix, to just hold it in main-memory and not on the filesystem.
+
As an alternative, you can also start the Derby-network-server seperately and connect by using the `properties.derby.client` instead.

. In case you want to use the datasource with JPA, provide a `persistence.xml`:
+
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
             http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">

	<persistence-unit name="prod" transaction-type="JTA">
		<jta-data-source>jdbc/defaultDatasource</jta-data-source>
		<properties>
			<property name="hibernate.show_sql" value="true" />
			<property name="eclipselink.logging.level" value="FINE" />
			<property name="javax.persistence.schema-generation.database.action" value="drop-and-create" />
			<property name="javax.persistence.schema-generation.scripts.action" value="drop-and-create" />
			<property name="javax.persistence.schema-generation.scripts.create-target" value="bootstrapCreate.ddl" />
			<property name="javax.persistence.schema-generation.scripts.drop-target" value="bootstrapDrop.ddl" />
		</properties>
	</persistence-unit>
</persistence>
----
+
With the default settings of Gradle's war-plugin, you can place it under `src/main/resources/META-INF` and the build should package it under `WEB-INF/classes/META-INF`.

. You should now be able to inject the entity-manager via
+
[source, java]
----
@PersistenceContext
EntityManager em;
----

link:https://blog.sebastian-daschner.com/entries/openliberty-with-postgres[This blog] has a similar guide on how to use PostgreSQL with Open Liberty.